// src/components/home/home.tsx
import * as React from 'react';
import './home.css';
import { Link } from 'react-router-dom';
import DoubleTextGenerator from '../../helpers/double-text';

export default class Home extends React.Component {
  render() {
    return (
      <div className="container">
        <div className="main-headline">
          <p className="yellow">News</p>
          <Link to="/104">
            <div className="option">
              {DoubleTextGenerator.CreateText('MAIN NEWS HEADLINE GOES HERE')}
              {DoubleTextGenerator.CreateText('104', 'yellow')}
            </div>
          </Link>
          <hr className="blue"/>
        </div>
        <div className="first-column">
          {this.getOption('A-Z HEADLINES', '199')}
          {this.getOption('BBC INFO', '695')}
          {this.getOption('CHILDREN', '500')}
          {this.getOption('COOKERY', '580')}
          {this.getOption('COMMUNITY', '650')}
          <div className="spacer" />
          {this.getOption('EDUCATION', '630')}
          {this.getOption('ENTERTAINMENT', '540')}
          {this.getOption('FILMS', '570')}
          {this.getOption('FINANCE', '200')}
          {this.getOption('HORSERACING', '660')}
          {this.getOption('LOTTERY', '555')}
          {this.getOption('MUSIC', '560')}
        </div>
        <div className="second-column">
          {this.getOption('NEWS HEADLINES', '101')}
          {this.getOption('NEWS FOR REGION', '160')}
          {this.getOption('NEWSROUND', '510')}
          {this.getOption('RADIO', '640')}
          {this.getOption('READ HEAR', '641')}
          <div className="spacer" />
          {this.getOption('SPORT', '300')}
          {this.getOption('SUBTITLING', '888')}
          {this.getOption('TRAVEL', '430')}
          {this.getOption('TV FEATURES', '590')}
          {this.getOption('TV LINKS', '615')}
          {this.getOption('TV LISTINGS', '600')}
          {this.getOption('WEATHER', '400')}
        </div>
        <div className="page-footer bluebg">
          <p className="yellow">Some interesting text goes here</p>
        </div>
      </div>
    );
  }

  getOption(text: string, pageNum: string) {
    return (
      <Link className="white" to={pageNum}>
        <div className="option">
          <p className="yellow">{text}</p>
          <p>{pageNum}</p>
        </div>
      </Link>
    );
  }
}

// src/components/pages/Home.svelte
<script lang="ts">
	import DoubleText from "../DoubleText.svelte";
	import Option from "../Option.svelte";
</script>

<style>
	.container {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.option {
		display: flex;
		justify-content: space-between;
	}

	.columns {
		display: flex;
		gap: 1rem;
	}

	.columns > div {
		display: flex;
		flex-direction: column;
		flex-grow: 1;
	}

	.spacer {
		height: 1rem;
	}

	hr.blue {
		border-color: blue;
		margin-bottom: 7px;
		margin-top: 7px;
		width: 100%;
	}

	.headline {
		display: flex;
		flex-direction: column;
  }
  
  .page-footer {
    text-align: center;
  }
</style>

<div class="container">
  <div class="headline">
    <p class="yellow">News</p>
    <a class="option" href="/104">
      <DoubleText text="MAIN NEWS HEADLINE GOES HERE" />
      <DoubleText text="104" foreground="yellow" />
    </a>
    <hr class="blue"/>
  </div>
  <div class="columns">
    <div>
      <Option text="A-Z HEADLINES" pageNumber="199" />
      <Option text="BBC INFO" pageNumber="695" />
      <Option text="CHILDREN" pageNumber="500" />
      <Option text="COOKERY" pageNumber="580" />
      <Option text="COMMUNITY" pageNumber="650" />
      <div class="spacer" />
      <Option text="EDUCATION" pageNumber="630" />
      <Option text="ENTERTAINMENT" pageNumber="540" />
      <Option text="FILMS" pageNumber="570" />
      <Option text="FINANCE" pageNumber="200" />
      <Option text="HORSERACING" pageNumber="660" />
      <Option text="LOTTERY" pageNumber="555" />
      <Option text="MUSIC" pageNumber="560" />
    </div>
    <div>
      <Option text="NEWS HEADLINES" pageNumber="101" />
      <Option text="NEWS FOR REGION" pageNumber="160" />
      <Option text="NEWSROUND" pageNumber="510" />
      <Option text="RADIO" pageNumber="640" />
      <Option text="READ HEAR" pageNumber="641" />
      <div class="spacer" />
      <Option text="SPORT" pageNumber="300" />
      <Option text="SUBTITLING" pageNumber="888" />
      <Option text="TRAVEL" pageNumber="430" />
      <Option text="TV FEATURES" pageNumber="590" />
      <Option text="TV LINKS" pageNumber="615" />
      <Option text="TV LISTINGS" pageNumber="600" />
      <Option text="WEATHER" pageNumber="400" />
    </div>
  </div>
  <div class="page-footer bluebg">
    <p class="yellow">Ceefax: The world at your fingertips</p>
  </div>
</div>
