// src/helpers/double-text.tsx
import * as React from 'react';

export default class DoubleTextGenerator {

  static CreateText(text: string, foreground: string = 'white', background: string = 'black', extraClasses: string = ''): JSX.Element {
    var lines: string[] = this.getLines(text);
    return (
      <div className={`doubleText ${extraClasses}`.trim()}>
        <span className={`${foreground} ${background}bg`}>
          {lines[0]}
        </span>
        <span className={`${foreground} ${background}bg`}>
          {lines[1]}
        </span>
      </div>);
  }

  static getLines(text: string): string[] {
    var lines: string[] = ['', ''];
    for (var i: number = 0; i < text.length; i++) {
      var val = text[i].charCodeAt(0);
      lines[0] += String.fromCharCode(val + 0xE000);
      lines[1] += String.fromCharCode(val + 0xE100);
    }
    return lines;
  }
}

// src/components/DoubleText.svelte
<script lang="ts">
  export let text: string;
  export let foreground: string = 'white';
  export let background: string = 'black';
  export let extraClasses: string = '';

  let lines: string[] = ['', ''];
  
  for (let i: number = 0; i < text.length; i++) {
    let val = text[i].charCodeAt(0);
    lines[0] += String.fromCharCode(val + 0xE000);
    lines[1] += String.fromCharCode(val + 0xE100);
  }
</script>

<style>
  .doubleText {
    display: flex;
    flex-direction: column;
  }
</style>

<div class={`doubleText ${extraClasses}`}>
  <span class={`${foreground} ${background}bg`}>
    {lines[0]}
  </span>
  <span class={`${foreground} ${background}bg`}>
    {lines[1]}
  </span>
</div>
